version: 2
jobs:
  build-and-test:
    docker:
      - image: ${STAGING_ECR_URL}/node-test
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    steps:
      - checkout
      - run:
          name: Install yarn
          command: npm install -g yarn@1.15.2
      - run:
          name: Build
          command: |
            cp ci/.npmrc .npmrc
            yarn install --frozen-lockfile
            yarn bootstrap
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Test
          command: yarn test
      - persist_to_workspace:
          root: "."
          paths:
            - ./**
  deploy-staging-site:
    docker:
      - image: ${STAGING_ECR_URL}/docker-deploy
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    environment:
      BUCKET: waffles
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: S3 Sync
          command: |
            export AWS_ACCESS_KEY_ID=${STAGING_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${STAGING_AWS_SECRET_ACCESS_KEY}
            aws s3 sync --delete --acl public-read packages/docs/catalog-doc-site/catalog/build s3://${BUCKET}.datacamp-staging.com/live
            #aws s3 sync --acl public-read packages/docs/catalog-doc-site/catalog/build/static/media s3://${BUCKET}.datacamp-staging.com/live/media
  deploy-doc-site:
    docker:
      - image: ${STAGING_ECR_URL}/docker-deploy
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    environment:
      BUCKET: waffles
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: S3 Sync
          command: |
            export AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
            aws s3 sync --delete --exclude "*le-components/*" --acl public-read packages/docs/catalog-doc-site/catalog/build s3://${BUCKET}.new.datacamp.com/live
            #aws s3 sync --acl public-read packages/docs/catalog-doc-site/catalog/build/static/media s3://${BUCKET}.new.datacamp.com/live/media
  publish-packages:
    docker:
      - image: ${STAGING_ECR_URL}/node-test
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: Lerna Publish
          command: yarn publish:ci
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-test:
          context: org-global
      - deploy-staging-site:
          requires:
            - build-and-test
          context: org-global
          filters:
            branches:
              ignore:
                - master
      - deploy-doc-site:
          requires:
            - build-and-test
          context: org-global
          filters:
            branches:
              only:
                - master
      - publish-packages:
          requires:
            - build-and-test
          context: org-global
          filters:
            branches:
              only:
                - master 
