version: 2.1
orbs:
  datacamp-ecr: datacamp/ecr@0
  datacamp-deploy: datacamp/deploy@1
  slack: circleci/slack@3.4.1
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - checkout
      - run:
          name: Copy NPM config
          command: cp ci/.npmrc .npmrc
      - run:
          name: Install lerna
          command: yarn global add lerna
      - run:
          name: Install and Build
          command: yarn bootstrap
      - persist_to_workspace:
          root: "."
          paths:
            - ./**
  test:
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Lint commits
          command: yarn commitlint:ci
      - run:
          name: Test
          command: yarn test
      - run:
          name: Check types
          command: yarn type-check
  cypress-test-storybook:
    docker:
      - image: cypress/browsers:node12.14.0-chrome79-ff71
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: Install cypress binaries
          command: yarn cypress install
          working_directory: ~/project/packages/docs/storybook
      - run:
          name: Launch storybook
          command: yarn start
          working_directory: ~/project/packages/docs/storybook
          background: true
      - run:
          name: Run cypress
          command: yarn cypress:ci
          working_directory: ~/project/packages/docs/storybook
  upload-to-percy:
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: Upload to percy
          command: yarn percy
  deploy-staging-site:
    docker:
      - image: ${STAGING_ECR_URL}/docker-deploy
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    environment:
      BUCKET: waffles
      CLOUDFRONT_ID: E16EOD0ZWD0L66
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: S3 Sync
          command: |
            export AWS_ACCESS_KEY_ID=${STAGING_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${STAGING_AWS_SECRET_ACCESS_KEY}
            aws s3 sync --delete --acl public-read packages/docs/catalog-doc-site/catalog/build s3://${BUCKET}.datacamp-staging.com/live
            #aws s3 sync --acl public-read packages/docs/catalog-doc-site/catalog/build/static/media s3://${BUCKET}.datacamp-staging.com/live/media
      - run:
          name: Invalidate Cache
          command: |
            export AWS_ACCESS_KEY_ID=$STAGING_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$STAGING_AWS_SECRET_ACCESS_KEY
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/index.html"
  deploy-doc-site:
    docker:
      - image: ${STAGING_ECR_URL}/docker-deploy
        aws_auth:
          aws_access_key_id: $STAGING_AWS_ACCESS_KEY_ID
          aws_secret_access_key: $STAGING_AWS_SECRET_ACCESS_KEY
    environment:
      BUCKET: waffles
      CLOUDFRONT_ID: E596C189UKISL
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: S3 Sync
          command: |
            export AWS_ACCESS_KEY_ID=${PROD_AWS_ACCESS_KEY_ID}
            export AWS_SECRET_ACCESS_KEY=${PROD_AWS_SECRET_ACCESS_KEY}
            aws s3 sync --delete --exclude "*le-components/*" --acl public-read packages/docs/catalog-doc-site/catalog/build s3://${BUCKET}.new.datacamp.com/live
            #aws s3 sync --acl public-read packages/docs/catalog-doc-site/catalog/build/static/media s3://${BUCKET}.new.datacamp.com/live/media
      - run:
          name: Invalidate Cache
          command: |
            export AWS_ACCESS_KEY_ID=$PROD_AWS_ACCESS_KEY_ID
            export AWS_SECRET_ACCESS_KEY=$PROD_AWS_SECRET_ACCESS_KEY
            aws cloudfront create-invalidation --distribution-id ${CLOUDFRONT_ID} --paths "/index.html"
  mutation-test:
    resource_class: xlarge
    docker:
      - image: circleci/node:12.4.0-browsers
    steps:
      - attach_workspace:
          at: "."
      - run:
          name: stryker mutation tests
          command: yarn stryker
      - persist_to_workspace:
          root: "."
          paths:
            - ./**
  send-to-slack:
    docker:
      - image: circleci/node
    steps:
      - slack/notify:
          message: Available to view at https://waffles-stryker-report.datacamp-staging.com/ (needs VPN)
          include_project_field: false
          include_job_number_field: false
          include_visit_job_action: false
          title: Check it party people, the mutation test results are in
          color: '#33aacc'
          channel: '#design-system-squad'
workflows:
  version: 2
  run_mutation_testing:
    triggers:
      - schedule:
          cron: "0 0 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - build:
          context: org-global
      - mutation-test:
          requires:
            - build
          context: org-global
      - datacamp-ecr/build_and_push_image_to_ecr:
          requires:
            - mutation-test
          name: push-stryker-image
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          repo: waffles-stryker-report
          pre-build-steps:
            - attach_workspace:
                at: "."
      - datacamp-deploy/deploy:
          name: deploy-stryker-report
          context: org-global
          new-deploy-opt-in: true
          deploy-url: $STAGING_LAMBDA_DEPLOY_URL
          deploy-password: $STAGING_LAMBDA_DEPLOY_PASSWORD
          requires:
            - push-stryker-image
      - send-to-slack:
          context: org-global
          requires:
            - deploy-stryker-report
  do_everything:
    jobs:
      - build:
          context: org-global
          filters:
            tags:
              only: /.*/
      - test:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /.*/
      - cypress-test-storybook:
          requires:
            - build
          context: org-global
          filters:
            tags:
              only: /.*/
      - hold-for-pr:
          type: approval
          context: org-global
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /master/
      - upload-to-percy:
          requires:
            - test
            - cypress-test-storybook
            - hold-for-pr
          context: org-global
      - datacamp-ecr/build_and_push_image_to_ecr:
          requires:
            - test
            - cypress-test-storybook
            - hold-for-pr
          name: push-storybook-image
          context: org-global
          aws-access-key-id: $STAGING_AWS_ACCESS_KEY_ID
          aws-secret-access-key: $STAGING_AWS_SECRET_ACCESS_KEY
          account-url: $STAGING_ECR_URL
          repo: waffles-storybook
          path: packages/docs/storybook
          dockerfile: packages/docs/storybook/Dockerfile
          pre-build-steps:
            - attach_workspace:
                at: "."
          filters:
            branches:
              ignore:
                - master
                - /dependabot.*/
      - datacamp-deploy/backstage-deploy: # backstage
          name: deploy-storybook
          context: org-global
          file: packages/docs/storybook/ecs.backstage.json
          extra-env: "BRANCH=${CIRCLE_BRANCH//\\//-}"
          new-deploy-opt-in: true
          deploy-url: $STAGING_LAMBDA_DEPLOY_URL
          deploy-password: $STAGING_LAMBDA_DEPLOY_PASSWORD
          requires:
            - push-storybook-image
      - deploy-staging-site:
          requires:
            - cypress-test-storybook
            - test
          context: org-global
          filters:
            branches:
              only:
                - staging
      - deploy-doc-site:
          requires:
            - cypress-test-storybook
            - test
          context: org-global
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
